
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const UserFlag = {
  RED: 'RED',
  WHITE: 'WHITE',
  GREEN: 'GREEN',
  YELLOW: 'YELLOW'
} as const

export type UserFlag = (typeof UserFlag)[keyof typeof UserFlag]


export const UserPermission = {
  FAQS: 'FAQS',
  KICK: 'KICK',
  USERS: 'USERS',
  CHATS: 'CHATS',
  SLOTS: 'SLOTS',
  BLOGS: 'BLOGS',
  MERCHS: 'MERCHS',
  REWARDS: 'REWARDS',
  CASINOS: 'CASINOS',
  PROVIDERS: 'PROVIDERS',
  LOOTBOXES: 'LOOTBOXES',
  MILESTONES: 'MILESTONES',
  BONUS_HUNTS: 'BONUS_HUNTS',
  POINTS_SHOP: 'POINTS_SHOP',
  PROMO_CODES: 'PROMO_CODES',
  TOURNAMENTS: 'TOURNAMENTS',
  LEADERBOARDS: 'LEADERBOARDS',
  WIN_TRACKERS: 'WIN_TRACKERS',
  SLOTS_BATTLES: 'SLOTS_BATTLES',
  NOTIFICATIONS: 'NOTIFICATIONS',
  SESSION_TRACKERS: 'SESSION_TRACKERS'
} as const

export type UserPermission = (typeof UserPermission)[keyof typeof UserPermission]
