
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Country` model and its related types.
 *
 * 🟢 You can import this file directly.
 */

import type * as PJTG from '../pjtg';
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Country
 * 
 */
export type CountryModel = runtime.Types.Result.DefaultSelection<Prisma.$CountryPayload>

export type AggregateCountry = {
  _count: CountryCountAggregateOutputType | null
  _min: CountryMinAggregateOutputType | null
  _max: CountryMaxAggregateOutputType | null
}

export type CountryMinAggregateOutputType = {
  countryCode: string | null
  currencyCode: string | null
  countryNameEn: string | null
  countryNameLocal: string | null
  currencyNameEn: string | null
  tinType: string | null
  tinName: string | null
  officialLanguageCode: string | null
  officialLanguageNameEn: string | null
  officialLanguageNameLocal: string | null
  countryCallingCode: string | null
  region: string | null
  flag: string | null
}

export type CountryMaxAggregateOutputType = {
  countryCode: string | null
  currencyCode: string | null
  countryNameEn: string | null
  countryNameLocal: string | null
  currencyNameEn: string | null
  tinType: string | null
  tinName: string | null
  officialLanguageCode: string | null
  officialLanguageNameEn: string | null
  officialLanguageNameLocal: string | null
  countryCallingCode: string | null
  region: string | null
  flag: string | null
}

export type CountryCountAggregateOutputType = {
  countryCode: number
  currencyCode: number
  countryNameEn: number
  countryNameLocal: number
  currencyNameEn: number
  tinType: number
  tinName: number
  officialLanguageCode: number
  officialLanguageNameEn: number
  officialLanguageNameLocal: number
  countryCallingCode: number
  region: number
  flag: number
  _all: number
}


export type CountryMinAggregateInputType = {
  countryCode?: true | runtime.Types.Skip
  currencyCode?: true | runtime.Types.Skip
  countryNameEn?: true | runtime.Types.Skip
  countryNameLocal?: true | runtime.Types.Skip
  currencyNameEn?: true | runtime.Types.Skip
  tinType?: true | runtime.Types.Skip
  tinName?: true | runtime.Types.Skip
  officialLanguageCode?: true | runtime.Types.Skip
  officialLanguageNameEn?: true | runtime.Types.Skip
  officialLanguageNameLocal?: true | runtime.Types.Skip
  countryCallingCode?: true | runtime.Types.Skip
  region?: true | runtime.Types.Skip
  flag?: true | runtime.Types.Skip
}

export type CountryMaxAggregateInputType = {
  countryCode?: true | runtime.Types.Skip
  currencyCode?: true | runtime.Types.Skip
  countryNameEn?: true | runtime.Types.Skip
  countryNameLocal?: true | runtime.Types.Skip
  currencyNameEn?: true | runtime.Types.Skip
  tinType?: true | runtime.Types.Skip
  tinName?: true | runtime.Types.Skip
  officialLanguageCode?: true | runtime.Types.Skip
  officialLanguageNameEn?: true | runtime.Types.Skip
  officialLanguageNameLocal?: true | runtime.Types.Skip
  countryCallingCode?: true | runtime.Types.Skip
  region?: true | runtime.Types.Skip
  flag?: true | runtime.Types.Skip
}

export type CountryCountAggregateInputType = {
  countryCode?: true | runtime.Types.Skip
  currencyCode?: true | runtime.Types.Skip
  countryNameEn?: true | runtime.Types.Skip
  countryNameLocal?: true | runtime.Types.Skip
  currencyNameEn?: true | runtime.Types.Skip
  tinType?: true | runtime.Types.Skip
  tinName?: true | runtime.Types.Skip
  officialLanguageCode?: true | runtime.Types.Skip
  officialLanguageNameEn?: true | runtime.Types.Skip
  officialLanguageNameLocal?: true | runtime.Types.Skip
  countryCallingCode?: true | runtime.Types.Skip
  region?: true | runtime.Types.Skip
  flag?: true | runtime.Types.Skip
  _all?: true | runtime.Types.Skip
}

export type CountryAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Country to aggregate.
   */
  where?: Prisma.CountryWhereInput | runtime.Types.Skip
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Countries to fetch.
   */
  orderBy?: Prisma.CountryOrderByWithRelationInput | Prisma.CountryOrderByWithRelationInput[] | runtime.Types.Skip
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.CountryWhereUniqueInput | runtime.Types.Skip
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Countries from the position of the cursor.
   */
  take?: number | runtime.Types.Skip
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Countries.
   */
  skip?: number | runtime.Types.Skip
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Countries
  **/
  _count?: true | CountryCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: CountryMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: CountryMaxAggregateInputType
}

export type GetCountryAggregateType<T extends CountryAggregateArgs> = {
      [P in keyof T & keyof AggregateCountry]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateCountry[P]>
    : Prisma.GetScalarType<T[P], AggregateCountry[P]>
}




export type CountryGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CountryWhereInput | runtime.Types.Skip
  orderBy?: Prisma.CountryOrderByWithAggregationInput | Prisma.CountryOrderByWithAggregationInput[] | runtime.Types.Skip
  by: Prisma.CountryScalarFieldEnum[] | Prisma.CountryScalarFieldEnum
  having?: Prisma.CountryScalarWhereWithAggregatesInput | runtime.Types.Skip
  take?: number | runtime.Types.Skip
  skip?: number | runtime.Types.Skip
  _count?: CountryCountAggregateInputType | true
  _min?: CountryMinAggregateInputType
  _max?: CountryMaxAggregateInputType
}

export type CountryGroupByOutputType = {
  countryCode: string
  currencyCode: string
  countryNameEn: string
  countryNameLocal: string
  currencyNameEn: string
  tinType: string
  tinName: string
  officialLanguageCode: string
  officialLanguageNameEn: string
  officialLanguageNameLocal: string
  countryCallingCode: string
  region: string
  flag: string
  _count: CountryCountAggregateOutputType | null
  _min: CountryMinAggregateOutputType | null
  _max: CountryMaxAggregateOutputType | null
}

type GetCountryGroupByPayload<T extends CountryGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<CountryGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof CountryGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], CountryGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], CountryGroupByOutputType[P]>
      }
    >
  >



export type CountryWhereInput = {
  AND?: Prisma.CountryWhereInput | Prisma.CountryWhereInput[] | runtime.Types.Skip
  OR?: Prisma.CountryWhereInput[] | runtime.Types.Skip
  NOT?: Prisma.CountryWhereInput | Prisma.CountryWhereInput[] | runtime.Types.Skip
  countryCode?: Prisma.StringFilter<"Country"> | string | runtime.Types.Skip
  currencyCode?: Prisma.StringFilter<"Country"> | string | runtime.Types.Skip
  countryNameEn?: Prisma.StringFilter<"Country"> | string | runtime.Types.Skip
  countryNameLocal?: Prisma.StringFilter<"Country"> | string | runtime.Types.Skip
  currencyNameEn?: Prisma.StringFilter<"Country"> | string | runtime.Types.Skip
  tinType?: Prisma.StringFilter<"Country"> | string | runtime.Types.Skip
  tinName?: Prisma.StringFilter<"Country"> | string | runtime.Types.Skip
  officialLanguageCode?: Prisma.StringFilter<"Country"> | string | runtime.Types.Skip
  officialLanguageNameEn?: Prisma.StringFilter<"Country"> | string | runtime.Types.Skip
  officialLanguageNameLocal?: Prisma.StringFilter<"Country"> | string | runtime.Types.Skip
  countryCallingCode?: Prisma.StringFilter<"Country"> | string | runtime.Types.Skip
  region?: Prisma.StringFilter<"Country"> | string | runtime.Types.Skip
  flag?: Prisma.StringFilter<"Country"> | string | runtime.Types.Skip
  users?: Prisma.UserListRelationFilter | runtime.Types.Skip
}

export type CountryOrderByWithRelationInput = {
  countryCode?: Prisma.SortOrder | runtime.Types.Skip
  currencyCode?: Prisma.SortOrder | runtime.Types.Skip
  countryNameEn?: Prisma.SortOrder | runtime.Types.Skip
  countryNameLocal?: Prisma.SortOrder | runtime.Types.Skip
  currencyNameEn?: Prisma.SortOrder | runtime.Types.Skip
  tinType?: Prisma.SortOrder | runtime.Types.Skip
  tinName?: Prisma.SortOrder | runtime.Types.Skip
  officialLanguageCode?: Prisma.SortOrder | runtime.Types.Skip
  officialLanguageNameEn?: Prisma.SortOrder | runtime.Types.Skip
  officialLanguageNameLocal?: Prisma.SortOrder | runtime.Types.Skip
  countryCallingCode?: Prisma.SortOrder | runtime.Types.Skip
  region?: Prisma.SortOrder | runtime.Types.Skip
  flag?: Prisma.SortOrder | runtime.Types.Skip
  users?: Prisma.UserOrderByRelationAggregateInput | runtime.Types.Skip
}

export type CountryWhereUniqueInput = Prisma.AtLeast<{
  countryCode?: string | runtime.Types.Skip
  AND?: Prisma.CountryWhereInput | Prisma.CountryWhereInput[] | runtime.Types.Skip
  OR?: Prisma.CountryWhereInput[] | runtime.Types.Skip
  NOT?: Prisma.CountryWhereInput | Prisma.CountryWhereInput[] | runtime.Types.Skip
  currencyCode?: Prisma.StringFilter<"Country"> | string | runtime.Types.Skip
  countryNameEn?: Prisma.StringFilter<"Country"> | string | runtime.Types.Skip
  countryNameLocal?: Prisma.StringFilter<"Country"> | string | runtime.Types.Skip
  currencyNameEn?: Prisma.StringFilter<"Country"> | string | runtime.Types.Skip
  tinType?: Prisma.StringFilter<"Country"> | string | runtime.Types.Skip
  tinName?: Prisma.StringFilter<"Country"> | string | runtime.Types.Skip
  officialLanguageCode?: Prisma.StringFilter<"Country"> | string | runtime.Types.Skip
  officialLanguageNameEn?: Prisma.StringFilter<"Country"> | string | runtime.Types.Skip
  officialLanguageNameLocal?: Prisma.StringFilter<"Country"> | string | runtime.Types.Skip
  countryCallingCode?: Prisma.StringFilter<"Country"> | string | runtime.Types.Skip
  region?: Prisma.StringFilter<"Country"> | string | runtime.Types.Skip
  flag?: Prisma.StringFilter<"Country"> | string | runtime.Types.Skip
  users?: Prisma.UserListRelationFilter | runtime.Types.Skip
}, "countryCode">

export type CountryOrderByWithAggregationInput = {
  countryCode?: Prisma.SortOrder | runtime.Types.Skip
  currencyCode?: Prisma.SortOrder | runtime.Types.Skip
  countryNameEn?: Prisma.SortOrder | runtime.Types.Skip
  countryNameLocal?: Prisma.SortOrder | runtime.Types.Skip
  currencyNameEn?: Prisma.SortOrder | runtime.Types.Skip
  tinType?: Prisma.SortOrder | runtime.Types.Skip
  tinName?: Prisma.SortOrder | runtime.Types.Skip
  officialLanguageCode?: Prisma.SortOrder | runtime.Types.Skip
  officialLanguageNameEn?: Prisma.SortOrder | runtime.Types.Skip
  officialLanguageNameLocal?: Prisma.SortOrder | runtime.Types.Skip
  countryCallingCode?: Prisma.SortOrder | runtime.Types.Skip
  region?: Prisma.SortOrder | runtime.Types.Skip
  flag?: Prisma.SortOrder | runtime.Types.Skip
  _count?: Prisma.CountryCountOrderByAggregateInput | runtime.Types.Skip
  _max?: Prisma.CountryMaxOrderByAggregateInput | runtime.Types.Skip
  _min?: Prisma.CountryMinOrderByAggregateInput | runtime.Types.Skip
}

export type CountryScalarWhereWithAggregatesInput = {
  AND?: Prisma.CountryScalarWhereWithAggregatesInput | Prisma.CountryScalarWhereWithAggregatesInput[] | runtime.Types.Skip
  OR?: Prisma.CountryScalarWhereWithAggregatesInput[] | runtime.Types.Skip
  NOT?: Prisma.CountryScalarWhereWithAggregatesInput | Prisma.CountryScalarWhereWithAggregatesInput[] | runtime.Types.Skip
  countryCode?: Prisma.StringWithAggregatesFilter<"Country"> | string | runtime.Types.Skip
  currencyCode?: Prisma.StringWithAggregatesFilter<"Country"> | string | runtime.Types.Skip
  countryNameEn?: Prisma.StringWithAggregatesFilter<"Country"> | string | runtime.Types.Skip
  countryNameLocal?: Prisma.StringWithAggregatesFilter<"Country"> | string | runtime.Types.Skip
  currencyNameEn?: Prisma.StringWithAggregatesFilter<"Country"> | string | runtime.Types.Skip
  tinType?: Prisma.StringWithAggregatesFilter<"Country"> | string | runtime.Types.Skip
  tinName?: Prisma.StringWithAggregatesFilter<"Country"> | string | runtime.Types.Skip
  officialLanguageCode?: Prisma.StringWithAggregatesFilter<"Country"> | string | runtime.Types.Skip
  officialLanguageNameEn?: Prisma.StringWithAggregatesFilter<"Country"> | string | runtime.Types.Skip
  officialLanguageNameLocal?: Prisma.StringWithAggregatesFilter<"Country"> | string | runtime.Types.Skip
  countryCallingCode?: Prisma.StringWithAggregatesFilter<"Country"> | string | runtime.Types.Skip
  region?: Prisma.StringWithAggregatesFilter<"Country"> | string | runtime.Types.Skip
  flag?: Prisma.StringWithAggregatesFilter<"Country"> | string | runtime.Types.Skip
}

export type CountryCreateInput = {
  countryCode: string
  currencyCode: string
  countryNameEn: string
  countryNameLocal: string
  currencyNameEn: string
  tinType: string
  tinName: string
  officialLanguageCode: string
  officialLanguageNameEn: string
  officialLanguageNameLocal: string
  countryCallingCode: string
  region: string
  flag: string
  users?: Prisma.UserCreateNestedManyWithoutCountryInput | runtime.Types.Skip
}

export type CountryUncheckedCreateInput = {
  countryCode: string
  currencyCode: string
  countryNameEn: string
  countryNameLocal: string
  currencyNameEn: string
  tinType: string
  tinName: string
  officialLanguageCode: string
  officialLanguageNameEn: string
  officialLanguageNameLocal: string
  countryCallingCode: string
  region: string
  flag: string
  users?: Prisma.UserUncheckedCreateNestedManyWithoutCountryInput | runtime.Types.Skip
}

export type CountryUpdateInput = {
  countryCode?: Prisma.StringFieldUpdateOperationsInput | string | runtime.Types.Skip
  currencyCode?: Prisma.StringFieldUpdateOperationsInput | string | runtime.Types.Skip
  countryNameEn?: Prisma.StringFieldUpdateOperationsInput | string | runtime.Types.Skip
  countryNameLocal?: Prisma.StringFieldUpdateOperationsInput | string | runtime.Types.Skip
  currencyNameEn?: Prisma.StringFieldUpdateOperationsInput | string | runtime.Types.Skip
  tinType?: Prisma.StringFieldUpdateOperationsInput | string | runtime.Types.Skip
  tinName?: Prisma.StringFieldUpdateOperationsInput | string | runtime.Types.Skip
  officialLanguageCode?: Prisma.StringFieldUpdateOperationsInput | string | runtime.Types.Skip
  officialLanguageNameEn?: Prisma.StringFieldUpdateOperationsInput | string | runtime.Types.Skip
  officialLanguageNameLocal?: Prisma.StringFieldUpdateOperationsInput | string | runtime.Types.Skip
  countryCallingCode?: Prisma.StringFieldUpdateOperationsInput | string | runtime.Types.Skip
  region?: Prisma.StringFieldUpdateOperationsInput | string | runtime.Types.Skip
  flag?: Prisma.StringFieldUpdateOperationsInput | string | runtime.Types.Skip
  users?: Prisma.UserUpdateManyWithoutCountryNestedInput | runtime.Types.Skip
}

export type CountryUncheckedUpdateInput = {
  countryCode?: Prisma.StringFieldUpdateOperationsInput | string | runtime.Types.Skip
  currencyCode?: Prisma.StringFieldUpdateOperationsInput | string | runtime.Types.Skip
  countryNameEn?: Prisma.StringFieldUpdateOperationsInput | string | runtime.Types.Skip
  countryNameLocal?: Prisma.StringFieldUpdateOperationsInput | string | runtime.Types.Skip
  currencyNameEn?: Prisma.StringFieldUpdateOperationsInput | string | runtime.Types.Skip
  tinType?: Prisma.StringFieldUpdateOperationsInput | string | runtime.Types.Skip
  tinName?: Prisma.StringFieldUpdateOperationsInput | string | runtime.Types.Skip
  officialLanguageCode?: Prisma.StringFieldUpdateOperationsInput | string | runtime.Types.Skip
  officialLanguageNameEn?: Prisma.StringFieldUpdateOperationsInput | string | runtime.Types.Skip
  officialLanguageNameLocal?: Prisma.StringFieldUpdateOperationsInput | string | runtime.Types.Skip
  countryCallingCode?: Prisma.StringFieldUpdateOperationsInput | string | runtime.Types.Skip
  region?: Prisma.StringFieldUpdateOperationsInput | string | runtime.Types.Skip
  flag?: Prisma.StringFieldUpdateOperationsInput | string | runtime.Types.Skip
  users?: Prisma.UserUncheckedUpdateManyWithoutCountryNestedInput | runtime.Types.Skip
}

export type CountryCreateManyInput = {
  countryCode: string
  currencyCode: string
  countryNameEn: string
  countryNameLocal: string
  currencyNameEn: string
  tinType: string
  tinName: string
  officialLanguageCode: string
  officialLanguageNameEn: string
  officialLanguageNameLocal: string
  countryCallingCode: string
  region: string
  flag: string
}

export type CountryUpdateManyMutationInput = {
  countryCode?: Prisma.StringFieldUpdateOperationsInput | string | runtime.Types.Skip
  currencyCode?: Prisma.StringFieldUpdateOperationsInput | string | runtime.Types.Skip
  countryNameEn?: Prisma.StringFieldUpdateOperationsInput | string | runtime.Types.Skip
  countryNameLocal?: Prisma.StringFieldUpdateOperationsInput | string | runtime.Types.Skip
  currencyNameEn?: Prisma.StringFieldUpdateOperationsInput | string | runtime.Types.Skip
  tinType?: Prisma.StringFieldUpdateOperationsInput | string | runtime.Types.Skip
  tinName?: Prisma.StringFieldUpdateOperationsInput | string | runtime.Types.Skip
  officialLanguageCode?: Prisma.StringFieldUpdateOperationsInput | string | runtime.Types.Skip
  officialLanguageNameEn?: Prisma.StringFieldUpdateOperationsInput | string | runtime.Types.Skip
  officialLanguageNameLocal?: Prisma.StringFieldUpdateOperationsInput | string | runtime.Types.Skip
  countryCallingCode?: Prisma.StringFieldUpdateOperationsInput | string | runtime.Types.Skip
  region?: Prisma.StringFieldUpdateOperationsInput | string | runtime.Types.Skip
  flag?: Prisma.StringFieldUpdateOperationsInput | string | runtime.Types.Skip
}

export type CountryUncheckedUpdateManyInput = {
  countryCode?: Prisma.StringFieldUpdateOperationsInput | string | runtime.Types.Skip
  currencyCode?: Prisma.StringFieldUpdateOperationsInput | string | runtime.Types.Skip
  countryNameEn?: Prisma.StringFieldUpdateOperationsInput | string | runtime.Types.Skip
  countryNameLocal?: Prisma.StringFieldUpdateOperationsInput | string | runtime.Types.Skip
  currencyNameEn?: Prisma.StringFieldUpdateOperationsInput | string | runtime.Types.Skip
  tinType?: Prisma.StringFieldUpdateOperationsInput | string | runtime.Types.Skip
  tinName?: Prisma.StringFieldUpdateOperationsInput | string | runtime.Types.Skip
  officialLanguageCode?: Prisma.StringFieldUpdateOperationsInput | string | runtime.Types.Skip
  officialLanguageNameEn?: Prisma.StringFieldUpdateOperationsInput | string | runtime.Types.Skip
  officialLanguageNameLocal?: Prisma.StringFieldUpdateOperationsInput | string | runtime.Types.Skip
  countryCallingCode?: Prisma.StringFieldUpdateOperationsInput | string | runtime.Types.Skip
  region?: Prisma.StringFieldUpdateOperationsInput | string | runtime.Types.Skip
  flag?: Prisma.StringFieldUpdateOperationsInput | string | runtime.Types.Skip
}

export type CountryCountOrderByAggregateInput = {
  countryCode?: Prisma.SortOrder | runtime.Types.Skip
  currencyCode?: Prisma.SortOrder | runtime.Types.Skip
  countryNameEn?: Prisma.SortOrder | runtime.Types.Skip
  countryNameLocal?: Prisma.SortOrder | runtime.Types.Skip
  currencyNameEn?: Prisma.SortOrder | runtime.Types.Skip
  tinType?: Prisma.SortOrder | runtime.Types.Skip
  tinName?: Prisma.SortOrder | runtime.Types.Skip
  officialLanguageCode?: Prisma.SortOrder | runtime.Types.Skip
  officialLanguageNameEn?: Prisma.SortOrder | runtime.Types.Skip
  officialLanguageNameLocal?: Prisma.SortOrder | runtime.Types.Skip
  countryCallingCode?: Prisma.SortOrder | runtime.Types.Skip
  region?: Prisma.SortOrder | runtime.Types.Skip
  flag?: Prisma.SortOrder | runtime.Types.Skip
}

export type CountryMaxOrderByAggregateInput = {
  countryCode?: Prisma.SortOrder | runtime.Types.Skip
  currencyCode?: Prisma.SortOrder | runtime.Types.Skip
  countryNameEn?: Prisma.SortOrder | runtime.Types.Skip
  countryNameLocal?: Prisma.SortOrder | runtime.Types.Skip
  currencyNameEn?: Prisma.SortOrder | runtime.Types.Skip
  tinType?: Prisma.SortOrder | runtime.Types.Skip
  tinName?: Prisma.SortOrder | runtime.Types.Skip
  officialLanguageCode?: Prisma.SortOrder | runtime.Types.Skip
  officialLanguageNameEn?: Prisma.SortOrder | runtime.Types.Skip
  officialLanguageNameLocal?: Prisma.SortOrder | runtime.Types.Skip
  countryCallingCode?: Prisma.SortOrder | runtime.Types.Skip
  region?: Prisma.SortOrder | runtime.Types.Skip
  flag?: Prisma.SortOrder | runtime.Types.Skip
}

export type CountryMinOrderByAggregateInput = {
  countryCode?: Prisma.SortOrder | runtime.Types.Skip
  currencyCode?: Prisma.SortOrder | runtime.Types.Skip
  countryNameEn?: Prisma.SortOrder | runtime.Types.Skip
  countryNameLocal?: Prisma.SortOrder | runtime.Types.Skip
  currencyNameEn?: Prisma.SortOrder | runtime.Types.Skip
  tinType?: Prisma.SortOrder | runtime.Types.Skip
  tinName?: Prisma.SortOrder | runtime.Types.Skip
  officialLanguageCode?: Prisma.SortOrder | runtime.Types.Skip
  officialLanguageNameEn?: Prisma.SortOrder | runtime.Types.Skip
  officialLanguageNameLocal?: Prisma.SortOrder | runtime.Types.Skip
  countryCallingCode?: Prisma.SortOrder | runtime.Types.Skip
  region?: Prisma.SortOrder | runtime.Types.Skip
  flag?: Prisma.SortOrder | runtime.Types.Skip
}

export type CountryScalarRelationFilter = {
  is?: Prisma.CountryWhereInput | runtime.Types.Skip
  isNot?: Prisma.CountryWhereInput | runtime.Types.Skip
}

export type StringFieldUpdateOperationsInput = {
  set?: string | runtime.Types.Skip
}

export type CountryCreateNestedOneWithoutUsersInput = {
  create?: Prisma.XOR<Prisma.CountryCreateWithoutUsersInput, Prisma.CountryUncheckedCreateWithoutUsersInput> | runtime.Types.Skip
  connectOrCreate?: Prisma.CountryCreateOrConnectWithoutUsersInput | runtime.Types.Skip
  connect?: Prisma.CountryWhereUniqueInput | runtime.Types.Skip
}

export type CountryUpdateOneRequiredWithoutUsersNestedInput = {
  create?: Prisma.XOR<Prisma.CountryCreateWithoutUsersInput, Prisma.CountryUncheckedCreateWithoutUsersInput> | runtime.Types.Skip
  connectOrCreate?: Prisma.CountryCreateOrConnectWithoutUsersInput | runtime.Types.Skip
  upsert?: Prisma.CountryUpsertWithoutUsersInput | runtime.Types.Skip
  connect?: Prisma.CountryWhereUniqueInput | runtime.Types.Skip
  update?: Prisma.XOR<Prisma.XOR<Prisma.CountryUpdateToOneWithWhereWithoutUsersInput, Prisma.CountryUpdateWithoutUsersInput>, Prisma.CountryUncheckedUpdateWithoutUsersInput> | runtime.Types.Skip
}

export type CountryCreateWithoutUsersInput = {
  countryCode: string
  currencyCode: string
  countryNameEn: string
  countryNameLocal: string
  currencyNameEn: string
  tinType: string
  tinName: string
  officialLanguageCode: string
  officialLanguageNameEn: string
  officialLanguageNameLocal: string
  countryCallingCode: string
  region: string
  flag: string
}

export type CountryUncheckedCreateWithoutUsersInput = {
  countryCode: string
  currencyCode: string
  countryNameEn: string
  countryNameLocal: string
  currencyNameEn: string
  tinType: string
  tinName: string
  officialLanguageCode: string
  officialLanguageNameEn: string
  officialLanguageNameLocal: string
  countryCallingCode: string
  region: string
  flag: string
}

export type CountryCreateOrConnectWithoutUsersInput = {
  where: Prisma.CountryWhereUniqueInput
  create: Prisma.XOR<Prisma.CountryCreateWithoutUsersInput, Prisma.CountryUncheckedCreateWithoutUsersInput>
}

export type CountryUpsertWithoutUsersInput = {
  update: Prisma.XOR<Prisma.CountryUpdateWithoutUsersInput, Prisma.CountryUncheckedUpdateWithoutUsersInput>
  create: Prisma.XOR<Prisma.CountryCreateWithoutUsersInput, Prisma.CountryUncheckedCreateWithoutUsersInput>
  where?: Prisma.CountryWhereInput | runtime.Types.Skip
}

export type CountryUpdateToOneWithWhereWithoutUsersInput = {
  where?: Prisma.CountryWhereInput | runtime.Types.Skip
  data: Prisma.XOR<Prisma.CountryUpdateWithoutUsersInput, Prisma.CountryUncheckedUpdateWithoutUsersInput>
}

export type CountryUpdateWithoutUsersInput = {
  countryCode?: Prisma.StringFieldUpdateOperationsInput | string | runtime.Types.Skip
  currencyCode?: Prisma.StringFieldUpdateOperationsInput | string | runtime.Types.Skip
  countryNameEn?: Prisma.StringFieldUpdateOperationsInput | string | runtime.Types.Skip
  countryNameLocal?: Prisma.StringFieldUpdateOperationsInput | string | runtime.Types.Skip
  currencyNameEn?: Prisma.StringFieldUpdateOperationsInput | string | runtime.Types.Skip
  tinType?: Prisma.StringFieldUpdateOperationsInput | string | runtime.Types.Skip
  tinName?: Prisma.StringFieldUpdateOperationsInput | string | runtime.Types.Skip
  officialLanguageCode?: Prisma.StringFieldUpdateOperationsInput | string | runtime.Types.Skip
  officialLanguageNameEn?: Prisma.StringFieldUpdateOperationsInput | string | runtime.Types.Skip
  officialLanguageNameLocal?: Prisma.StringFieldUpdateOperationsInput | string | runtime.Types.Skip
  countryCallingCode?: Prisma.StringFieldUpdateOperationsInput | string | runtime.Types.Skip
  region?: Prisma.StringFieldUpdateOperationsInput | string | runtime.Types.Skip
  flag?: Prisma.StringFieldUpdateOperationsInput | string | runtime.Types.Skip
}

export type CountryUncheckedUpdateWithoutUsersInput = {
  countryCode?: Prisma.StringFieldUpdateOperationsInput | string | runtime.Types.Skip
  currencyCode?: Prisma.StringFieldUpdateOperationsInput | string | runtime.Types.Skip
  countryNameEn?: Prisma.StringFieldUpdateOperationsInput | string | runtime.Types.Skip
  countryNameLocal?: Prisma.StringFieldUpdateOperationsInput | string | runtime.Types.Skip
  currencyNameEn?: Prisma.StringFieldUpdateOperationsInput | string | runtime.Types.Skip
  tinType?: Prisma.StringFieldUpdateOperationsInput | string | runtime.Types.Skip
  tinName?: Prisma.StringFieldUpdateOperationsInput | string | runtime.Types.Skip
  officialLanguageCode?: Prisma.StringFieldUpdateOperationsInput | string | runtime.Types.Skip
  officialLanguageNameEn?: Prisma.StringFieldUpdateOperationsInput | string | runtime.Types.Skip
  officialLanguageNameLocal?: Prisma.StringFieldUpdateOperationsInput | string | runtime.Types.Skip
  countryCallingCode?: Prisma.StringFieldUpdateOperationsInput | string | runtime.Types.Skip
  region?: Prisma.StringFieldUpdateOperationsInput | string | runtime.Types.Skip
  flag?: Prisma.StringFieldUpdateOperationsInput | string | runtime.Types.Skip
}


/**
 * Count Type CountryCountOutputType
 */

export type CountryCountOutputType = {
  users: number
}

export type CountryCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  users?: boolean | CountryCountOutputTypeCountUsersArgs
}

/**
 * CountryCountOutputType without action
 */
export type CountryCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CountryCountOutputType
   */
  select?: Prisma.CountryCountOutputTypeSelect<ExtArgs> | null
}

/**
 * CountryCountOutputType without action
 */
export type CountryCountOutputTypeCountUsersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.UserWhereInput | runtime.Types.Skip
}


export type CountrySelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  countryCode?: boolean | runtime.Types.Skip
  currencyCode?: boolean | runtime.Types.Skip
  countryNameEn?: boolean | runtime.Types.Skip
  countryNameLocal?: boolean | runtime.Types.Skip
  currencyNameEn?: boolean | runtime.Types.Skip
  tinType?: boolean | runtime.Types.Skip
  tinName?: boolean | runtime.Types.Skip
  officialLanguageCode?: boolean | runtime.Types.Skip
  officialLanguageNameEn?: boolean | runtime.Types.Skip
  officialLanguageNameLocal?: boolean | runtime.Types.Skip
  countryCallingCode?: boolean | runtime.Types.Skip
  region?: boolean | runtime.Types.Skip
  flag?: boolean | runtime.Types.Skip
  users?: boolean | Prisma.Country$usersArgs<ExtArgs> | runtime.Types.Skip
  _count?: boolean | Prisma.CountryCountOutputTypeDefaultArgs<ExtArgs> | runtime.Types.Skip
}, ExtArgs["result"]["country"]>

export type CountrySelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  countryCode?: boolean | runtime.Types.Skip
  currencyCode?: boolean | runtime.Types.Skip
  countryNameEn?: boolean | runtime.Types.Skip
  countryNameLocal?: boolean | runtime.Types.Skip
  currencyNameEn?: boolean | runtime.Types.Skip
  tinType?: boolean | runtime.Types.Skip
  tinName?: boolean | runtime.Types.Skip
  officialLanguageCode?: boolean | runtime.Types.Skip
  officialLanguageNameEn?: boolean | runtime.Types.Skip
  officialLanguageNameLocal?: boolean | runtime.Types.Skip
  countryCallingCode?: boolean | runtime.Types.Skip
  region?: boolean | runtime.Types.Skip
  flag?: boolean | runtime.Types.Skip
}, ExtArgs["result"]["country"]>

export type CountrySelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  countryCode?: boolean | runtime.Types.Skip
  currencyCode?: boolean | runtime.Types.Skip
  countryNameEn?: boolean | runtime.Types.Skip
  countryNameLocal?: boolean | runtime.Types.Skip
  currencyNameEn?: boolean | runtime.Types.Skip
  tinType?: boolean | runtime.Types.Skip
  tinName?: boolean | runtime.Types.Skip
  officialLanguageCode?: boolean | runtime.Types.Skip
  officialLanguageNameEn?: boolean | runtime.Types.Skip
  officialLanguageNameLocal?: boolean | runtime.Types.Skip
  countryCallingCode?: boolean | runtime.Types.Skip
  region?: boolean | runtime.Types.Skip
  flag?: boolean | runtime.Types.Skip
}, ExtArgs["result"]["country"]>

export type CountrySelectScalar = {
  countryCode?: boolean | runtime.Types.Skip
  currencyCode?: boolean | runtime.Types.Skip
  countryNameEn?: boolean | runtime.Types.Skip
  countryNameLocal?: boolean | runtime.Types.Skip
  currencyNameEn?: boolean | runtime.Types.Skip
  tinType?: boolean | runtime.Types.Skip
  tinName?: boolean | runtime.Types.Skip
  officialLanguageCode?: boolean | runtime.Types.Skip
  officialLanguageNameEn?: boolean | runtime.Types.Skip
  officialLanguageNameLocal?: boolean | runtime.Types.Skip
  countryCallingCode?: boolean | runtime.Types.Skip
  region?: boolean | runtime.Types.Skip
  flag?: boolean | runtime.Types.Skip
}

export type CountryOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"countryCode" | "currencyCode" | "countryNameEn" | "countryNameLocal" | "currencyNameEn" | "tinType" | "tinName" | "officialLanguageCode" | "officialLanguageNameEn" | "officialLanguageNameLocal" | "countryCallingCode" | "region" | "flag", ExtArgs["result"]["country"], runtime.Types.Skip>
export type CountryInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  users?: boolean | Prisma.Country$usersArgs<ExtArgs> | runtime.Types.Skip
  _count?: boolean | Prisma.CountryCountOutputTypeDefaultArgs<ExtArgs> | runtime.Types.Skip
}
export type CountryIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type CountryIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $CountryPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Country"
  objects: {
    users: Prisma.$UserPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    countryCode: string
    currencyCode: string
    countryNameEn: string
    countryNameLocal: string
    currencyNameEn: string
    tinType: string
    tinName: string
    officialLanguageCode: string
    officialLanguageNameEn: string
    officialLanguageNameLocal: string
    countryCallingCode: string
    region: string
    flag: string
  }, ExtArgs["result"]["country"]>
  composites: {}
}

export type CountryGetPayload<S extends boolean | null | undefined | CountryDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$CountryPayload, S>

export type CountryCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<CountryFindManyArgs, 'select' | 'include' | 'distinct' | 'omit' | 'relationLoadStrategy'> & {
    select?: CountryCountAggregateInputType | true
  }

export interface CountryDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Country'], meta: { name: 'Country' } }
  /**
   * Find zero or one Country that matches the filter.
   * @param {CountryFindUniqueArgs} args - Arguments to find a Country
   * @example
   * // Get one Country
   * const country = await prisma.country.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends CountryFindUniqueArgs>(args: Prisma.SelectSubset<T, CountryFindUniqueArgs<ExtArgs>>): Prisma.Prisma__CountryClient<runtime.Types.Result.GetResult<Prisma.$CountryPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Country that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {CountryFindUniqueOrThrowArgs} args - Arguments to find a Country
   * @example
   * // Get one Country
   * const country = await prisma.country.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends CountryFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, CountryFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__CountryClient<runtime.Types.Result.GetResult<Prisma.$CountryPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Country that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CountryFindFirstArgs} args - Arguments to find a Country
   * @example
   * // Get one Country
   * const country = await prisma.country.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends CountryFindFirstArgs>(args?: Prisma.SelectSubset<T, CountryFindFirstArgs<ExtArgs>>): Prisma.Prisma__CountryClient<runtime.Types.Result.GetResult<Prisma.$CountryPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Country that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CountryFindFirstOrThrowArgs} args - Arguments to find a Country
   * @example
   * // Get one Country
   * const country = await prisma.country.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends CountryFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, CountryFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__CountryClient<runtime.Types.Result.GetResult<Prisma.$CountryPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Countries that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CountryFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Countries
   * const countries = await prisma.country.findMany()
   * 
   * // Get first 10 Countries
   * const countries = await prisma.country.findMany({ take: 10 })
   * 
   * // Only select the `countryCode`
   * const countryWithCountryCodeOnly = await prisma.country.findMany({ select: { countryCode: true } })
   * 
   */
  findMany<T extends CountryFindManyArgs>(args?: Prisma.SelectSubset<T, CountryFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CountryPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Country.
   * @param {CountryCreateArgs} args - Arguments to create a Country.
   * @example
   * // Create one Country
   * const Country = await prisma.country.create({
   *   data: {
   *     // ... data to create a Country
   *   }
   * })
   * 
   */
  create<T extends CountryCreateArgs>(args: Prisma.SelectSubset<T, CountryCreateArgs<ExtArgs>>): Prisma.Prisma__CountryClient<runtime.Types.Result.GetResult<Prisma.$CountryPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Countries.
   * @param {CountryCreateManyArgs} args - Arguments to create many Countries.
   * @example
   * // Create many Countries
   * const country = await prisma.country.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends CountryCreateManyArgs>(args?: Prisma.SelectSubset<T, CountryCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Countries and returns the data saved in the database.
   * @param {CountryCreateManyAndReturnArgs} args - Arguments to create many Countries.
   * @example
   * // Create many Countries
   * const country = await prisma.country.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Countries and only return the `countryCode`
   * const countryWithCountryCodeOnly = await prisma.country.createManyAndReturn({
   *   select: { countryCode: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends CountryCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, CountryCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CountryPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Country.
   * @param {CountryDeleteArgs} args - Arguments to delete one Country.
   * @example
   * // Delete one Country
   * const Country = await prisma.country.delete({
   *   where: {
   *     // ... filter to delete one Country
   *   }
   * })
   * 
   */
  delete<T extends CountryDeleteArgs>(args: Prisma.SelectSubset<T, CountryDeleteArgs<ExtArgs>>): Prisma.Prisma__CountryClient<runtime.Types.Result.GetResult<Prisma.$CountryPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Country.
   * @param {CountryUpdateArgs} args - Arguments to update one Country.
   * @example
   * // Update one Country
   * const country = await prisma.country.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends CountryUpdateArgs>(args: Prisma.SelectSubset<T, CountryUpdateArgs<ExtArgs>>): Prisma.Prisma__CountryClient<runtime.Types.Result.GetResult<Prisma.$CountryPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Countries.
   * @param {CountryDeleteManyArgs} args - Arguments to filter Countries to delete.
   * @example
   * // Delete a few Countries
   * const { count } = await prisma.country.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends CountryDeleteManyArgs>(args?: Prisma.SelectSubset<T, CountryDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Countries.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CountryUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Countries
   * const country = await prisma.country.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends CountryUpdateManyArgs>(args: Prisma.SelectSubset<T, CountryUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Countries and returns the data updated in the database.
   * @param {CountryUpdateManyAndReturnArgs} args - Arguments to update many Countries.
   * @example
   * // Update many Countries
   * const country = await prisma.country.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Countries and only return the `countryCode`
   * const countryWithCountryCodeOnly = await prisma.country.updateManyAndReturn({
   *   select: { countryCode: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends CountryUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, CountryUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CountryPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Country.
   * @param {CountryUpsertArgs} args - Arguments to update or create a Country.
   * @example
   * // Update or create a Country
   * const country = await prisma.country.upsert({
   *   create: {
   *     // ... data to create a Country
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Country we want to update
   *   }
   * })
   */
  upsert<T extends CountryUpsertArgs>(args: Prisma.SelectSubset<T, CountryUpsertArgs<ExtArgs>>): Prisma.Prisma__CountryClient<runtime.Types.Result.GetResult<Prisma.$CountryPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Countries.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CountryCountArgs} args - Arguments to filter Countries to count.
   * @example
   * // Count the number of Countries
   * const count = await prisma.country.count({
   *   where: {
   *     // ... the filter for the Countries we want to count
   *   }
   * })
  **/
  count<T extends CountryCountArgs>(
    args?: Prisma.Subset<T, CountryCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], CountryCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Country.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CountryAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends CountryAggregateArgs>(args: Prisma.Subset<T, CountryAggregateArgs>): Prisma.PrismaPromise<GetCountryAggregateType<T>>

  /**
   * Group by Country.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CountryGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends CountryGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: CountryGroupByArgs['orderBy'] }
      : { orderBy?: CountryGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, CountryGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetCountryGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Country model
 */
readonly fields: CountryFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Country.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__CountryClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  users<T extends Prisma.Country$usersArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Country$usersArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Country model
 */
export interface CountryFieldRefs {
  readonly countryCode: Prisma.FieldRef<"Country", 'String'>
  readonly currencyCode: Prisma.FieldRef<"Country", 'String'>
  readonly countryNameEn: Prisma.FieldRef<"Country", 'String'>
  readonly countryNameLocal: Prisma.FieldRef<"Country", 'String'>
  readonly currencyNameEn: Prisma.FieldRef<"Country", 'String'>
  readonly tinType: Prisma.FieldRef<"Country", 'String'>
  readonly tinName: Prisma.FieldRef<"Country", 'String'>
  readonly officialLanguageCode: Prisma.FieldRef<"Country", 'String'>
  readonly officialLanguageNameEn: Prisma.FieldRef<"Country", 'String'>
  readonly officialLanguageNameLocal: Prisma.FieldRef<"Country", 'String'>
  readonly countryCallingCode: Prisma.FieldRef<"Country", 'String'>
  readonly region: Prisma.FieldRef<"Country", 'String'>
  readonly flag: Prisma.FieldRef<"Country", 'String'>
}
    

// Custom InputTypes
/**
 * Country findUnique
 */
export type CountryFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Country
   */
  select?: Prisma.CountrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Country
   */
  omit?: Prisma.CountryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CountryInclude<ExtArgs> | null
  /**
   * Filter, which Country to fetch.
   */
  where: Prisma.CountryWhereUniqueInput
  relationLoadStrategy?: Prisma.RelationLoadStrategy | runtime.Types.Skip
}

/**
 * Country findUniqueOrThrow
 */
export type CountryFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Country
   */
  select?: Prisma.CountrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Country
   */
  omit?: Prisma.CountryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CountryInclude<ExtArgs> | null
  /**
   * Filter, which Country to fetch.
   */
  where: Prisma.CountryWhereUniqueInput
  relationLoadStrategy?: Prisma.RelationLoadStrategy | runtime.Types.Skip
}

/**
 * Country findFirst
 */
export type CountryFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Country
   */
  select?: Prisma.CountrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Country
   */
  omit?: Prisma.CountryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CountryInclude<ExtArgs> | null
  /**
   * Filter, which Country to fetch.
   */
  where?: Prisma.CountryWhereInput | runtime.Types.Skip
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Countries to fetch.
   */
  orderBy?: Prisma.CountryOrderByWithRelationInput | Prisma.CountryOrderByWithRelationInput[] | runtime.Types.Skip
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Countries.
   */
  cursor?: Prisma.CountryWhereUniqueInput | runtime.Types.Skip
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Countries from the position of the cursor.
   */
  take?: number | runtime.Types.Skip
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Countries.
   */
  skip?: number | runtime.Types.Skip
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Countries.
   */
  distinct?: Prisma.CountryScalarFieldEnum | Prisma.CountryScalarFieldEnum[] | runtime.Types.Skip
  relationLoadStrategy?: Prisma.RelationLoadStrategy | runtime.Types.Skip
}

/**
 * Country findFirstOrThrow
 */
export type CountryFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Country
   */
  select?: Prisma.CountrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Country
   */
  omit?: Prisma.CountryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CountryInclude<ExtArgs> | null
  /**
   * Filter, which Country to fetch.
   */
  where?: Prisma.CountryWhereInput | runtime.Types.Skip
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Countries to fetch.
   */
  orderBy?: Prisma.CountryOrderByWithRelationInput | Prisma.CountryOrderByWithRelationInput[] | runtime.Types.Skip
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Countries.
   */
  cursor?: Prisma.CountryWhereUniqueInput | runtime.Types.Skip
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Countries from the position of the cursor.
   */
  take?: number | runtime.Types.Skip
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Countries.
   */
  skip?: number | runtime.Types.Skip
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Countries.
   */
  distinct?: Prisma.CountryScalarFieldEnum | Prisma.CountryScalarFieldEnum[] | runtime.Types.Skip
  relationLoadStrategy?: Prisma.RelationLoadStrategy | runtime.Types.Skip
}

/**
 * Country findMany
 */
export type CountryFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Country
   */
  select?: Prisma.CountrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Country
   */
  omit?: Prisma.CountryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CountryInclude<ExtArgs> | null
  /**
   * Filter, which Countries to fetch.
   */
  where?: Prisma.CountryWhereInput | runtime.Types.Skip
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Countries to fetch.
   */
  orderBy?: Prisma.CountryOrderByWithRelationInput | Prisma.CountryOrderByWithRelationInput[] | runtime.Types.Skip
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Countries.
   */
  cursor?: Prisma.CountryWhereUniqueInput | runtime.Types.Skip
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Countries from the position of the cursor.
   */
  take?: number | runtime.Types.Skip
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Countries.
   */
  skip?: number | runtime.Types.Skip
  distinct?: Prisma.CountryScalarFieldEnum | Prisma.CountryScalarFieldEnum[] | runtime.Types.Skip
  relationLoadStrategy?: Prisma.RelationLoadStrategy | runtime.Types.Skip
}

/**
 * Country create
 */
export type CountryCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Country
   */
  select?: Prisma.CountrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Country
   */
  omit?: Prisma.CountryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CountryInclude<ExtArgs> | null
  /**
   * The data needed to create a Country.
   */
  data: Prisma.XOR<Prisma.CountryCreateInput, Prisma.CountryUncheckedCreateInput>
  relationLoadStrategy?: Prisma.RelationLoadStrategy | runtime.Types.Skip
}

/**
 * Country createMany
 */
export type CountryCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Countries.
   */
  data: Prisma.CountryCreateManyInput | Prisma.CountryCreateManyInput[]
  skipDuplicates?: boolean | runtime.Types.Skip
}

/**
 * Country createManyAndReturn
 */
export type CountryCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Country
   */
  select?: Prisma.CountrySelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Country
   */
  omit?: Prisma.CountryOmit<ExtArgs> | null
  /**
   * The data used to create many Countries.
   */
  data: Prisma.CountryCreateManyInput | Prisma.CountryCreateManyInput[]
  skipDuplicates?: boolean | runtime.Types.Skip
}

/**
 * Country update
 */
export type CountryUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Country
   */
  select?: Prisma.CountrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Country
   */
  omit?: Prisma.CountryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CountryInclude<ExtArgs> | null
  /**
   * The data needed to update a Country.
   */
  data: Prisma.XOR<Prisma.CountryUpdateInput, Prisma.CountryUncheckedUpdateInput>
  /**
   * Choose, which Country to update.
   */
  where: Prisma.CountryWhereUniqueInput
  relationLoadStrategy?: Prisma.RelationLoadStrategy | runtime.Types.Skip
}

/**
 * Country updateMany
 */
export type CountryUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Countries.
   */
  data: Prisma.XOR<Prisma.CountryUpdateManyMutationInput, Prisma.CountryUncheckedUpdateManyInput>
  /**
   * Filter which Countries to update
   */
  where?: Prisma.CountryWhereInput | runtime.Types.Skip
  /**
   * Limit how many Countries to update.
   */
  limit?: number | runtime.Types.Skip
}

/**
 * Country updateManyAndReturn
 */
export type CountryUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Country
   */
  select?: Prisma.CountrySelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Country
   */
  omit?: Prisma.CountryOmit<ExtArgs> | null
  /**
   * The data used to update Countries.
   */
  data: Prisma.XOR<Prisma.CountryUpdateManyMutationInput, Prisma.CountryUncheckedUpdateManyInput>
  /**
   * Filter which Countries to update
   */
  where?: Prisma.CountryWhereInput | runtime.Types.Skip
  /**
   * Limit how many Countries to update.
   */
  limit?: number | runtime.Types.Skip
}

/**
 * Country upsert
 */
export type CountryUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Country
   */
  select?: Prisma.CountrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Country
   */
  omit?: Prisma.CountryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CountryInclude<ExtArgs> | null
  /**
   * The filter to search for the Country to update in case it exists.
   */
  where: Prisma.CountryWhereUniqueInput
  /**
   * In case the Country found by the `where` argument doesn't exist, create a new Country with this data.
   */
  create: Prisma.XOR<Prisma.CountryCreateInput, Prisma.CountryUncheckedCreateInput>
  /**
   * In case the Country was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.CountryUpdateInput, Prisma.CountryUncheckedUpdateInput>
  relationLoadStrategy?: Prisma.RelationLoadStrategy | runtime.Types.Skip
}

/**
 * Country delete
 */
export type CountryDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Country
   */
  select?: Prisma.CountrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Country
   */
  omit?: Prisma.CountryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CountryInclude<ExtArgs> | null
  /**
   * Filter which Country to delete.
   */
  where: Prisma.CountryWhereUniqueInput
  relationLoadStrategy?: Prisma.RelationLoadStrategy | runtime.Types.Skip
}

/**
 * Country deleteMany
 */
export type CountryDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Countries to delete
   */
  where?: Prisma.CountryWhereInput | runtime.Types.Skip
  /**
   * Limit how many Countries to delete.
   */
  limit?: number | runtime.Types.Skip
}

/**
 * Country.users
 */
export type Country$usersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  where?: Prisma.UserWhereInput | runtime.Types.Skip
  orderBy?: Prisma.UserOrderByWithRelationInput | Prisma.UserOrderByWithRelationInput[] | runtime.Types.Skip
  cursor?: Prisma.UserWhereUniqueInput | runtime.Types.Skip
  take?: number | runtime.Types.Skip
  skip?: number | runtime.Types.Skip
  distinct?: Prisma.UserScalarFieldEnum | Prisma.UserScalarFieldEnum[] | runtime.Types.Skip
}

/**
 * Country without action
 */
export type CountryDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Country
   */
  select?: Prisma.CountrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Country
   */
  omit?: Prisma.CountryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CountryInclude<ExtArgs> | null
}
